//! Failure register (Reflexion): repeated failing actions across runs.
//!
//! Derived view (`memory/derived/failures.md`), generated by
//! `mini-agi run failures`, never hand-edited. A fresh session reads it
//! through `resume` so recorded failures are not repeated (ADR-0005,
//! TICKET-9: reactive-loop repeated the identical failing edit three
//! times with zero reflection).

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::eval::Run;
use crate::hash::fact_id;

/// MAST failure taxonomy (arXiv 2503.13657): 14 empirically grounded
/// failure modes in 3 categories. `loop dispatch` injects classified
/// failures into rerun context; `run failures` validates against this.
pub const MAST_MODES: &[(&str, &str)] = &[
    ("FM-1.1", "disobey task specification"),
    ("FM-1.2", "disobey role specification"),
    ("FM-1.3", "step repetition"),
    ("FM-1.4", "loss of conversation history"),
    ("FM-1.5", "unaware of stopping conditions"),
    ("FM-2.1", "conversation reset"),
    ("FM-2.2", "fail to ask for clarification"),
    ("FM-2.3", "task derailment"),
    ("FM-2.4", "information withholding"),
    ("FM-2.5", "ignored other agent's input"),
    ("FM-2.6", "reasoning-action mismatch"),
    ("FM-3.1", "premature termination"),
    ("FM-3.2", "no or incomplete verification"),
    ("FM-3.3", "incorrect verification"),
];

/// Normalize machine-specific absolute path prefixes in an action text
/// so fact ids are stable across hosts (Phase 9 slice 1). The stored
/// action keeps the original text for display.
///
/// The explicit machine prefixes cover this host's tree; ANY user's
/// home (`/home/<user>/`) normalizes too — a fact id must be stable
/// across hosts, not just across this machine's own paths.
#[must_use]
pub fn normalize_action(action: &str) -> String {
    let mut out = action.to_string();
    for prefix in ["/mnt/storage/", "/tmp/opencode/", "/tmp/"] {
        out = out.replace(prefix, "<abs>/");
    }
    normalize_any_home(&out)
}

/// `/home/<user>/...` -> `<abs>/...` for ANY user segment (a host's
/// username is machine-specific; two hosts recording the same failure
/// under different homes must hash identically).
fn normalize_any_home(s: &str) -> String {
    let mut out = String::new();
    let mut rest = s;
    loop {
        let Some(pos) = rest.find("/home/") else {
            out.push_str(rest);
            return out;
        };
        out.push_str(&rest[..pos]);
        let after = &rest[pos + "/home/".len()..];
        let (user, tail) = after.split_once('/').unwrap_or((after, ""));
        if user.is_empty() {
            out.push_str("/home/");
            rest = tail;
            continue;
        }
        out.push_str("<abs>/");
        rest = tail;
    }
}

/// One recorded repeated failing action.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct FailureEntry {
    /// `fact_id("tool|action")` — 16-hex content hash.
    pub hash: String,
    /// Tool used for the repeated action.
    pub tool: String,
    /// Action payload text.
    pub action: String,
    /// Number of occurrences in the run.
    pub count: usize,
    /// 1-based step indices of the occurrences.
    pub steps: Vec<u32>,
    /// Case name (parent dir of the run file).
    pub case: String,
    /// Verbal self-reflection on the failure (Reflexion; absent in
    /// entries recorded before Phase 8).
    #[serde(default)]
    pub reflection: Option<String>,
    /// MAST classification (e.g. `FM-1.3 step repetition`).
    #[serde(default)]
    pub mast: Option<String>,
    /// Verifier status of the run, recorded when the run declares a
    /// verifier (Phase 9 slice 3 — evidence-gated memory: entries
    /// carry executable evidence, not speculation).
    #[serde(default)]
    pub verifier: Option<String>,
}

/// Register file path under a repo root.
#[must_use]
pub fn register_path(root: &Path) -> PathBuf {
    root.join("memory/derived/failures.md")
}

/// Find repeated identical `(tool, action)` pairs that carry at least one
/// failure signal (`ok == Some(false)` or `goal_aligned == Some(false)`).
///
/// Clean repeats (e.g. re-running the same test after different fixes)
/// are not failures and are not flagged.
#[must_use]
pub fn repeated_failing_actions(run: &Run) -> Vec<(String, String, usize, Vec<u32>)> {
    let mut groups: Vec<(String, String, usize, Vec<u32>, bool)> = Vec::new();
    for step in &run.trajectory {
        let failed = step.ok == Some(false) || step.goal_aligned == Some(false);
        match groups
            .iter_mut()
            .find(|g| g.0 == step.tool && g.1 == step.action)
        {
            Some(g) => {
                g.2 += 1;
                g.3.push(step.step);
                g.4 |= failed;
            }
            None => groups.push((
                step.tool.clone(),
                step.action.clone(),
                1,
                vec![step.step],
                failed,
            )),
        }
    }
    groups.sort();
    groups
        .into_iter()
        .filter(|(_, _, count, _, failed)| *count >= 2 && *failed)
        .map(|(tool, action, count, steps, _)| (tool, action, count, steps))
        .collect()
}

/// Analyze one run file: the case name plus its failure entries.
///
/// # Errors
///
/// Returns a message when the file is missing, malformed, or fails run
/// validation.
pub fn analyze_run(run_path: &Path, _root: &Path) -> Result<(String, Vec<FailureEntry>), String> {
    let text = fs::read_to_string(run_path)
        .map_err(|e| format!("cannot read {}: {e}", run_path.display()))?;
    let run: Run = serde_json::from_str(&text).map_err(|e| format!("invalid run json: {e}"))?;
    Run::validate(&run).map_err(|e| format!("invalid run: {e}"))?;
    if let Some(mast) = &run.mast
        && !MAST_MODES.iter().any(|(id, name)| {
            mast == *id || mast.eq_ignore_ascii_case(name) || mast == &format!("{id} {name}")
        })
    {
        return Err(format!(
            "invalid run: mast '{mast}' is not one of the 14 MAST modes (arXiv 2503.13657)"
        ));
    }
    let case = run_path.parent().and_then(|p| p.file_name()).map_or_else(
        || "unknown".to_string(),
        |n| n.to_string_lossy().into_owned(),
    );
    // Evidence-gating without executing (codex review, ADR-0011 trust
    // boundary: only `run verify`/`loop verify` execute verifiers):
    // record the DECLARED verifier; actual verification happens in the
    // verify commands, not in `run failures`.
    let verifier = run.verify_command.is_some().then(|| "declared".to_string());
    let entries = repeated_failing_actions(&run)
        .into_iter()
        .map(|(tool, action, count, steps)| FailureEntry {
            hash: fact_id(&format!("{}|{}", tool, normalize_action(&action))),
            tool,
            action: normalize_action(&action),
            count,
            steps,
            case: case.clone(),
            reflection: run.reflection.clone(),
            mast: run.mast.clone(),
            verifier: verifier.clone(),
        })
        .collect();
    Ok((case, entries))
}

/// Read the register file; an absent file is an empty register.
///
/// # Errors
///
/// Returns the underlying filesystem error on unreadable files.
pub fn read_register(root: &Path) -> io::Result<Vec<FailureEntry>> {
    let text = fs::read_to_string(register_path(root))?;
    let mut out = Vec::new();
    for line in text.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        if let Ok(entry) = serde_json::from_str::<FailureEntry>(line) {
            out.push(entry);
        }
    }
    Ok(out)
}

/// Merge entries into the register: one entry per `(case, hash)`, sorted by
/// `(case, hash)`, written deterministically.
///
/// # Errors
///
/// Returns the underlying filesystem or serialization error.
pub fn update_register(root: &Path, new_entries: &[FailureEntry]) -> io::Result<usize> {
    let mut existing = read_register(root).unwrap_or_default();
    for entry in new_entries {
        existing.retain(|e| !(e.case == entry.case && e.hash == entry.hash));
        existing.push(entry.clone());
    }
    existing.sort_by(|a, b| a.case.cmp(&b.case).then_with(|| a.hash.cmp(&b.hash)));
    let path = register_path(root);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut out = String::from(
        "# FAILURE REGISTER (derived — generated by `mini-agi run failures`, never hand-edit)\n",
    );
    for entry in &existing {
        let line = serde_json::to_string(entry).map_err(io::Error::other)?;
        out.push_str(&line);
        out.push('\n');
    }
    fs::write(&path, out)?;
    Ok(existing.len())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;
    use std::path::Path;

    fn case_run(case: &str) -> (String, Vec<FailureEntry>) {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../evals/cases")
            .join(case)
            .join("run.json");
        analyze_run(
            &path,
            &Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../")
                .canonicalize()
                .unwrap(),
        )
        .unwrap()
    }

    #[test]
    fn flags_repeated_failing_action_in_reactive_loop() {
        let (case, entries) = case_run("reactive-loop");
        assert_eq!(case, "reactive-loop");
        assert_eq!(entries.len(), 1);
        let e = &entries[0];
        assert_eq!(e.tool, "edit");
        assert_eq!(e.action, "edit same line");
        assert_eq!(e.count, 2);
        assert_eq!(e.steps, vec![4, 6]);
        assert_eq!(e.hash, fact_id("edit|edit same line"));
    }

    #[test]
    fn clean_repeats_are_not_failures() {
        let (_, entries) = case_run("real-ticket-008-v2");
        assert!(entries.is_empty());
    }

    #[test]
    fn register_merges_deterministically_and_idempotently() {
        let root = env::temp_dir().join(format!("mag-failure-reg-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        let e = FailureEntry {
            hash: fact_id("edit|edit same line"),
            tool: "edit".into(),
            action: "edit same line".into(),
            count: 2,
            steps: vec![4, 6],
            case: "reactive-loop".into(),
            reflection: Some("repeated the identical failing edit three times without reading the verifier output — plan the fix before editing".into()),
            mast: Some("FM-1.3 step repetition".into()),
            verifier: Some("unverified".into()),
        };
        assert_eq!(update_register(&root, std::slice::from_ref(&e)).unwrap(), 1);
        assert_eq!(update_register(&root, std::slice::from_ref(&e)).unwrap(), 1);
        let other = FailureEntry {
            hash: fact_id("exec|make verify"),
            tool: "exec".into(),
            action: "make verify".into(),
            count: 3,
            steps: vec![3, 5, 7],
            case: "reactive-loop".into(),
            reflection: None,
            mast: Some("FM-3.2 no or incomplete verification".into()),
            verifier: None,
        };
        assert_eq!(update_register(&root, &[other]).unwrap(), 2);
        let read = read_register(&root).unwrap();
        assert_eq!(read.len(), 2);
        let mut actions: Vec<&str> = read.iter().map(|e| e.action.as_str()).collect();
        actions.sort_unstable();
        assert_eq!(actions, vec!["edit same line", "make verify"]);
        assert!(
            read.iter()
                .any(|e| e.mast.as_deref() == Some("FM-1.3 step repetition"))
        );
        assert!(read.iter().any(|e| e.reflection.is_some()));
        let _ = fs::remove_dir_all(&root);
    }
}

#[cfg(test)]
mod normalization_tests {
    use super::*;
    use crate::eval::{Outcome, Run, Step};

    #[test]
    fn absolute_paths_normalize_for_hashing() {
        let a = "write: const patch = \"/home/krn/proj/src/main.rs\"";
        let b = "write: const patch = \"/tmp/opencode/proj/src/main.rs\"";
        assert_eq!(normalize_action(a), normalize_action(b));
        assert_eq!(
            fact_id(&format!("write|{}", normalize_action(a))),
            fact_id(&format!("write|{}", normalize_action(b)))
        );
        assert_eq!(normalize_action("edit same line"), "edit same line");
    }

    #[test]
    fn longest_absolute_prefix_wins_in_normalization() {
        // "/tmp/opencode/" must win over "/tmp/" — the nested prefix is
        // checked first, so a session dir does not degrade to
        // "<abs>/opencode/...".
        assert_eq!(
            normalize_action("run: /tmp/opencode/session/a"),
            "run: <abs>/session/a"
        );
        // Any /tmp path normalizes via the shorter prefix.
        assert_eq!(normalize_action("run: /tmp/x"), "run: <abs>/x");
        assert_eq!(
            normalize_action("run: /tmp/opencode2/y"),
            "run: <abs>/opencode2/y"
        );
        assert_eq!(
            normalize_action("run: /home/krn/proj/src/main.rs"),
            "run: <abs>/proj/src/main.rs"
        );
        assert_eq!(normalize_action("no abs paths"), "no abs paths");
    }

    #[test]
    fn any_users_home_normalizes_for_hashing() {
        // The register's contract: fact ids are stable ACROSS HOSTS. A
        // hardcoded prefix list normalizes THIS machine's /home/krn/,
        // but another user's home (/home/alice/) stayed raw — the same
        // failure recorded on two hosts produced two different hashes
        // and the cross-host dedup silently failed.
        let a = "write: const patch = \"/home/alice/proj/src/main.rs\"";
        let b = "write: const patch = \"/home/krn/proj/src/main.rs\"";
        assert_eq!(normalize_action(a), normalize_action(b));
        assert_eq!(
            fact_id(&format!("write|{}", normalize_action(a))),
            fact_id(&format!("write|{}", normalize_action(b)))
        );
        // The explicit machine prefixes keep working.
        assert_eq!(
            normalize_action("run: /home/alice/proj/src/main.rs"),
            "run: <abs>/proj/src/main.rs"
        );
        assert_eq!(
            normalize_action("run: /home/krn/proj/src/main.rs"),
            "run: <abs>/proj/src/main.rs"
        );
    }

    #[test]
    fn repeat_with_any_failure_signal_is_flagged() {
        let mut run = Run {
            goal: "g".into(),
            scope: vec![],
            outcome: Outcome {
                achieved: true,
                tests_pass: None,
                typecheck_pass: None,
                lint_pass: None,
            },
            tokens_total: 0,
            cost_usd: 0.0,
            golden: None,
            verify_command: None,
            verify_target: None,
            reflection: None,
            mast: None,
            trajectory: vec![
                Step {
                    step: 1,
                    action: "cargo test".into(),
                    tool: "exec".into(),
                    ok: Some(true),
                    goal_aligned: None,
                    tokens: 0,
                    output_tokens: 0,
                    reverted: false,
                    note: String::new(),
                    paths: vec![],
                },
                Step {
                    step: 2,
                    action: "cargo test".into(),
                    tool: "exec".into(),
                    ok: Some(false),
                    goal_aligned: None,
                    tokens: 0,
                    output_tokens: 0,
                    reverted: false,
                    note: String::new(),
                    paths: vec![],
                },
                Step {
                    step: 3,
                    action: "cargo test".into(),
                    tool: "exec".into(),
                    ok: Some(true),
                    goal_aligned: None,
                    tokens: 0,
                    output_tokens: 0,
                    reverted: false,
                    note: String::new(),
                    paths: vec![],
                },
            ],
            kernel_version: None,
            n_steps: None,
            n_toolcalls: None,
            mode: None,
            latency_seconds: None,
            extra: serde_json::Map::new(),
        };
        // Interleaved failing step: the repeat is flagged with the full
        // count and every 1-based index, in order.
        let found = repeated_failing_actions(&run);
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].0, "exec");
        assert_eq!(found[0].1, "cargo test");
        assert_eq!(found[0].2, 3);
        assert_eq!(found[0].3, vec![1, 2, 3]);
        // One clean run of the same action is not a repeat at all.
        run.trajectory.truncate(1);
        run.trajectory[0].ok = Some(true);
        assert!(repeated_failing_actions(&run).is_empty());
    }
}
