//! Tool-mismatch register (Phase 6.2): where runs diverge from the golden.
//!
//! Derived view (`memory/derived/mismatches.md`), generated by
//! `mini-agi eval mismatches`, never hand-edited. A fresh session reads it
//! through `resume` so the next run of a case starts knowing the exact
//! steps where its tool use diverged from the golden trajectory
//! (ADR-0005: the failure signal must change the next run).

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::eval;
use crate::hash::fact_id;

/// One recorded tool mismatch: the run's step vs the golden's expectation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MismatchEntry {
    /// `fact_id("case|step|run_tool|golden_tool")` — 16-hex content hash.
    pub hash: String,
    /// Case name (parent dir of the run file).
    pub case: String,
    /// 1-based step number in the run trajectory.
    pub step: usize,
    /// Tool the run used at this step.
    pub run_tool: String,
    /// Tool the golden trajectory expects at this step.
    pub golden_tool: String,
}

/// Register file path under a repo root.
#[must_use]
pub fn register_path(root: &Path) -> PathBuf {
    root.join("memory/derived/mismatches.md")
}

/// Analyze one run file: the case name plus its mismatch entries.
///
/// # Errors
///
/// Returns a message when the file is missing, malformed, or fails run
/// validation.
pub fn analyze_run(
    run_path: &Path,
    golden_dir: &Path,
    root: &Path,
) -> Result<(String, Vec<MismatchEntry>), String> {
    let text = fs::read_to_string(run_path)
        .map_err(|e| format!("cannot read {}: {e}", run_path.display()))?;
    let run: eval::Run =
        serde_json::from_str(&text).map_err(|e| format!("invalid run json: {e}"))?;
    eval::Run::validate(&run).map_err(|e| format!("invalid run: {e}"))?;
    let case = run_path.parent().and_then(|p| p.file_name()).map_or_else(
        || "unknown".to_string(),
        |n| n.to_string_lossy().into_owned(),
    );
    let report = eval::score_run(run_path, root, golden_dir)
        .map_err(|e| format!("cannot score {}: {e}", run_path.display()))?;
    let entries = report
        .tool_mismatches_detail
        .into_iter()
        .map(|m| MismatchEntry {
            hash: fact_id(&format!(
                "{}|{}|{}|{}",
                case, m.step, m.run_tool, m.golden_tool
            )),
            case: case.clone(),
            step: m.step,
            run_tool: m.run_tool,
            golden_tool: m.golden_tool,
        })
        .collect();
    Ok((case, entries))
}

/// Read the register file; an absent file is an empty register.
///
/// # Errors
///
/// Returns the underlying filesystem error on unreadable files.
pub fn read_register(root: &Path) -> io::Result<Vec<MismatchEntry>> {
    let text = fs::read_to_string(register_path(root))?;
    let mut out = Vec::new();
    for line in text.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        if let Ok(entry) = serde_json::from_str::<MismatchEntry>(line) {
            out.push(entry);
        }
    }
    Ok(out)
}

/// Merge entries into the register: one entry per `(case, step)`, sorted by
/// `(case, step)`, written deterministically.
///
/// # Errors
///
/// Returns the underlying filesystem or serialization error.
pub fn update_register(root: &Path, new_entries: &[MismatchEntry]) -> io::Result<usize> {
    let mut existing = read_register(root).unwrap_or_default();
    for entry in new_entries {
        existing.retain(|e| !(e.case == entry.case && e.step == entry.step));
        existing.push(entry.clone());
    }
    existing.sort_by(|a, b| a.case.cmp(&b.case).then_with(|| a.step.cmp(&b.step)));
    let path = register_path(root);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut out = String::from(
        "# TOOL MISMATCH REGISTER (derived — generated by `mini-agi eval mismatches`, never hand-edit)\n",
    );
    for entry in &existing {
        let line = serde_json::to_string(entry).map_err(io::Error::other)?;
        out.push_str(&line);
        out.push('\n');
    }
    fs::write(&path, out)?;
    Ok(existing.len())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;

    fn root() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../")
            .canonicalize()
            .unwrap()
    }

    fn case_run(case: &str) -> (String, Vec<MismatchEntry>) {
        let repo = root();
        let path = repo.join("evals/cases").join(case).join("run.json");
        analyze_run(&path, &repo.join("evals/golden"), &repo).unwrap()
    }

    #[test]
    fn real_ticket_001_reports_exact_mismatch_steps() {
        let (case, entries) = case_run("real-ticket-001-v2");
        assert_eq!(case, "real-ticket-001-v2");
        let steps: Vec<usize> = entries.iter().map(|e| e.step).collect();
        assert_eq!(steps, vec![2, 3, 4, 6]);
        let e = &entries[0];
        assert_eq!(
            (e.run_tool.as_str(), e.golden_tool.as_str()),
            ("exec", "write")
        );
    }

    #[test]
    fn clean_case_has_no_mismatches() {
        let (_, entries) = case_run("real-ticket-008-v2");
        assert!(entries.is_empty());
    }

    #[test]
    fn register_merges_deterministically_and_idempotently() {
        let tmp = env::temp_dir().join(format!("mag-mismatch-reg-{}", std::process::id()));
        let _ = fs::remove_dir_all(&tmp);
        let e = MismatchEntry {
            hash: fact_id("c|2|exec|write"),
            case: "c".into(),
            step: 2,
            run_tool: "exec".into(),
            golden_tool: "write".into(),
        };
        assert_eq!(update_register(&tmp, std::slice::from_ref(&e)).unwrap(), 1);
        assert_eq!(update_register(&tmp, std::slice::from_ref(&e)).unwrap(), 1);
        let other = MismatchEntry {
            hash: fact_id("c|3|read|write"),
            case: "c".into(),
            step: 3,
            run_tool: "read".into(),
            golden_tool: "write".into(),
        };
        assert_eq!(update_register(&tmp, &[other]).unwrap(), 2);
        let read = read_register(&tmp).unwrap();
        assert_eq!(read.len(), 2);
        assert_eq!(read[0].step, 2);
        assert_eq!(read[1].step, 3);
        let _ = fs::remove_dir_all(&tmp);
    }

    #[test]
    fn analyze_run_error_paths_are_named() {
        let tmp = env::temp_dir().join(format!("mag-mismatch-err-{}", std::process::id()));
        let _ = fs::remove_dir_all(&tmp);
        // Missing file: named, never a crash.
        assert!(
            analyze_run(&tmp.join("run.json"), &tmp.join("golden"), &tmp)
                .unwrap_err()
                .contains("cannot read"),
        );
        // Malformed JSON and empty-trajectory runs map to their errors.
        let run = tmp.join("case1/run.json");
        fs::create_dir_all(run.parent().unwrap()).unwrap();
        fs::write(&run, "{not-json").unwrap();
        assert!(
            analyze_run(&run, &tmp.join("golden"), &tmp)
                .unwrap_err()
                .contains("invalid run json"),
        );
        fs::write(
            &run,
            r#"{"goal":"g","scope":[],"outcome":{"achieved":false},"trajectory":[]}"#,
        )
        .unwrap();
        assert!(
            analyze_run(&run, &tmp.join("golden"), &tmp)
                .unwrap_err()
                .contains("invalid run"),
        );
        let _ = fs::remove_dir_all(&tmp);
    }

    #[test]
    fn read_register_tolerates_comments_and_junk_lines() {
        let tmp = env::temp_dir().join(format!("mag-mismatch-junk-{}", std::process::id()));
        let _ = fs::remove_dir_all(&tmp);
        fs::create_dir_all(register_path(&tmp).parent().unwrap()).unwrap();
        let e = MismatchEntry {
            hash: fact_id("c|1|exec|write"),
            case: "c".into(),
            step: 1,
            run_tool: "exec".into(),
            golden_tool: "write".into(),
        };
        let json = serde_json::to_string(&e).unwrap();
        fs::write(
            register_path(&tmp),
            format!("# mismatch register\n\n{json}\n{{not-json}}\n"),
        )
        .unwrap();
        let read = read_register(&tmp).unwrap();
        assert_eq!(read.len(), 1, "comments and junk lines are tolerated");
        assert_eq!(read[0].hash, e.hash);
        let _ = fs::remove_dir_all(&tmp);
    }
}
